---
version: '3'

services:
  ajv-validator:
    image: onsdigital/eq-questionnaire-validator:${TAG}-ajv
    networks:
      - eq-schema
    ports:
      - 5002:5002

  py-validator:
    image: onsdigital/eq-questionnaire-validator:${TAG}
    healthcheck:
      test: "curl -f localhost:5002"
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - eq-schema
    environment:
      AJV_HOST: ajv-validator
    ports:
      - 5001:5000
    depends_on:
      - ajv-validator
networks:
  eq-schema:
    driver: bridge
