---
version: '3'

services:
  ajv-validator:
    image: europe-west2-docker.pkg.dev/ons-eq-ci/docker-images/eq-questionnaire-validator-ajv:latest
    networks:
      - eq-schema
    ports:
      - 5002:5002
    healthcheck:
      test: "curl localhost:5002/status"
      interval: 5s
      timeout: 5s
      retries: 20

  py-validator:
    image: europe-west2-docker.pkg.dev/ons-eq-ci/docker-images/eq-questionnaire-validator:latest
    networks:
      - eq-schema
    environment:
      AJV_VALIDATOR_HOST: ajv-validator
    ports:
      - 5001:5000
    depends_on:
      ajv-validator:
        condition: service_healthy
networks:
  eq-schema:
    driver: bridge
