name: Release

on:
  release:
    types: [published]

jobs:
  add-schemas-to-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Zip artifacts
        run: zip -r schemas.zip schemas
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: schemas.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
