name: Release

on: pull_request

jobs:
  add-templates-to-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip artifacts
        run: zip -r schemas.zip schemas